name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rename spec file if needed
        run: |
          if [ -f buildozer.spec.ini ]; then
            mv buildozer.spec.ini buildozer.spec
          fi

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools python3 \
            git unzip zip \
            openjdk-17-jdk \
            autoconf automake libtool pkg-config \
            libjpeg-dev zlib1g-dev

      - name: Install Python & Buildozer deps
        run: |
          pip install --upgrade pip
          pip install cython buildozer docwriter

      - name: Patch macro usage for missing libtool macros (safe fallback)
        run: echo 'm4_pattern_allow([LT_SYS_SYMBOL_USCORE])' > allow_missing_macros.m4

      - name: Build APK
        run: buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
